spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/userdb
    #url: jdbc:postgresql://host.docker.internal:5432/userdb
    username: user
    password: secret
  jpa:
    hibernate:
      ddl-auto: update   # change to validate in prod
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
server:
  port: 8083
